# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  name: 'agpoolwebresume'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
      addToPath: true
  
  # Step 2: Install dependencies
  - script: |
      python3.10 --version
      python3.10 -m pip install --upgrade pip
    displayName: 'verify dependencies'

  - script : |
      python3.10 -m pip install -r requirements.txt
    displayName: 'Install dependencies'
  
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/functionapp.zip'
      replaceExistingArchive: true

  - task: AzureFunctionApp@1
    inputs:
      azureSubscription: 'AzureServiceConnections'
      appType: 'FunctionAppLinux'
      appName: 'fnapproledescriptions'
      package: '$(Build.ArtifactStagingDirectory)/functionapp.zip'