# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  name: 'agpoolwebresume'

variables:
  pythonVersion: '3.10.17'

steps:
- task: UsePythonVersion@0 
  inputs:
    versionSpec: $(pythonVersion)
    addToPath: true

- script : |
    python -m venv .venv
    source  .venv/bin/activate
    pip install -r requirements.txt
  displayName: 'install dependencies'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/functionapp.zip'
    replaceExistingArchive: true

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'AzureServiceConnections'
    appType: 'FunctionAppLinux'
    appName: 'fnapproledescriptions'
    package: '$(Build.ArtifactStagingDirectory)/functionapp.zip'